### ISSUE TITLE
Autosave feature on Chat Page

### ISSUE THREAD

**Issue by Plant-0-0** [RSynapse/NB2-Knowledge#11]
![image](https://github.com/RSynapse/NB2-Knowledge/assets/155495277/5c7559cf-247a-49c5-824b-b7a0d6a7f48d)

I want to be able to title anything in the new chat and then click OUTSIDE of the box and that it autosaves...similar to Windows Explorer when I retitle a file and then click away and it autosaves.

**Comment by RSynapse** [comment]
Completed
