### ISSUE TITLE
Feedback Button

### ISSUE THREAD

**Issue by Plant-0-0** [RSynapse/NB2-Knowledge#6]
Add Feedback Buttons on the splash page https://narrative-buddy.com/

Underneath "Get Started" Add a phrase that says "We're in our soft launch, help us Improve Narrative Buddy!" 

Underneath it add a button similar to the "Get Started" button that says "Submit Feedback" and link it to the Suggestions channel in Discord. 

Goal is for users to submit feedback from any page on NB within 5 clicks and in less than 60 seconds. 

- [x] Feedback Button titled "Submit Feedback via Discord" on Splash Page that links to Discord. It can look like the Get Started Button but with a lighter blue hue. Include the Discord logo in the button
- [x] Feedback Button underneath titled "Submit Feedback via Narrative Buddy" that links to [Contact Us ](https://narrative-buddy.com/contact-us/)page
- [x] Similar Feedback Button titled "Suggestions" on top of all NB pages in the top banner line of the page, between "About" and "Blog", that also links to the "Contact Us" page (since the Discord option is already included.) 
- [x] Check for functionality

**Comment by RSynapse** [comment]
Instead of labeling the third point suggestions, it will be labeled Contact Us.  It's more in line with industry standard.

**Comment by Plant-0-0** [comment]
![image](https://github.com/RSynapse/NB2-Knowledge/assets/155495277/cfa65fee-f8b7-4360-9de1-619b7f728dc6)
 Link to discord from splash page doesn't work...maybe i did something wrong
